"""Generate contracts/boundaries.md from contracts/boundaries.json, the schemas and the fixtures.

Each boundary shows: sender, receiver, transport, request and result schema, a real valid request and result,
a real rejected request and result with the reason, and what each side does on failure. A boundary with no result def says it is
one-way. boundaries.json may carry request_case and result_case ({"valid": i, "invalid": j}) to choose which fixture example is shown.
Usage: python boundary_sheets.py [--check]
"""
import copy
import json
import sys
from pathlib import Path

from jsonschema import Draft202012Validator, FormatChecker
from jsonschema.exceptions import best_match
from referencing import Registry, Resource

V = Path(__file__).resolve().parent.parent
C = V / 'contracts'
CHECK = '--check' in sys.argv

schemas = {p.name: json.loads(p.read_text(encoding='utf-8')) for p in sorted(C.glob('*.schema.json'))}
resources = {s['$id']: s for s in schemas.values()}
for p in (V / 'exports/schemas').rglob('*.json'):
    s = json.loads(p.read_text(encoding='utf-8'))
    if '$id' in s:
        resources[s['$id']] = s
registry = Registry().with_resources((k, Resource.from_contents(v)) for k, v in resources.items())

# the sample generator used by validate_services.py (valid example from a schema)
src = (Path(__file__).parent / 'validate_services.py').read_text(encoding='utf-8').split('names = [')[0]
ns = {'__file__': str(Path(__file__).parent / 'validate_services.py')}
old_argv = sys.argv
sys.argv = [sys.argv[0], str(V.parents[1])]
exec(compile(src, 'validate_services_head', 'exec'), ns)
sys.argv = old_argv
sample = ns['sample']
services = schemas['services-v1.schema.json']

fixtures = {}
for p in sorted((C / 'fixtures').glob('*.json')) if (C / 'fixtures').exists() else []:
    f = json.loads(p.read_text(encoding='utf-8'))
    for case in f['cases']:
        fixtures[(f['schema'], case['def'])] = case


def split(ref):
    s, d = ref.split('#')
    return s, d


def validator(sname, d):
    return Draft202012Validator({'$ref': f"{schemas[sname]['$id']}#/$defs/{d}"}, registry=registry, format_checker=FormatChecker())


def examples(ref, pick=None):
    sname, d = split(ref)
    pick = pick or {}
    if (sname, d) in fixtures:
        case = fixtures[(sname, d)]
        valid, invalid = case['valid'][pick.get('valid', 0)], case['invalid'][pick.get('invalid', 0)]
    else:
        body = schemas[sname]['$defs'][d]
        valid = sample(body)
        invalid = copy.deepcopy(valid)
        req = body.get('required', [])
        if req:
            del invalid[req[-1]]
        else:
            invalid['unknown_field'] = True
    v = validator(sname, d)
    errs = list(v.iter_errors(invalid))
    best = best_match(errs) if errs else None
    where = '.'.join(str(x) for x in best.absolute_path) if best is not None and best.absolute_path else 'root'
    why = f'{where}: {best.message[:140]}' if best is not None else 'accepted: example is not invalid'
    return valid, invalid, why


def short(obj, limit=900):
    t = json.dumps(obj, indent=2, ensure_ascii=False)
    return t if len(t) <= limit else t[:limit].rsplit('\n', 1)[0] + '\n  ...'


def render():
    data = json.loads((C / 'boundaries.json').read_text(encoding='utf-8'))
    bs = data['boundaries']
    nodes = {}

    short_names = {'Client (CLI, web, benchmark)': 'Client', 'Benchmark client': 'Client', 'CC runner or planner': 'CC runner',
                   'Runner or supervisor': 'Supervisor', 'Human via CLI': 'Human', 'Restricted tool child': 'Tool child',
                   'Event bus and views': 'Event views', 'Binder (freeze)': 'Binder'}

    def node(name):
        name = short_names.get(name, name)
        key = ''.join(c for c in name if c.isalnum())
        nodes[key] = name
        return key
    edges = []
    for b in bs:
        edges.append(f'  {node(b["sender"])} -->|"{b["id"]}"| {node(b["receiver"])}')
    out = ['---', 'id: contracts.boundaries', 'type: generated', 'level: detail', 'status: draft', 'version: 1',
           'provides: []', 'depends_on: [README.md, principles.md, ../system/modules.md]', 'prd: []',
           'prd_note: generated sheet of module boundaries; clauses are on the pages it links', 'tags: [contracts, boundaries]', '---', '',
           '# Boundary sheets: where modules talk', '',
           'Generated by `python _tools/boundary_sheets.py` from `contracts/boundaries.json`, the schemas and the fixtures. Do not edit by hand. Rules for messages: [principles](principles.md). Module blocks: [modules](../system/modules.md).', '',
           '## Map', '', '```mermaid', 'flowchart LR']
    out += [f'  {k}["{v}"]' for k, v in nodes.items()]
    out += edges
    out += ['```', '', '## Index', '', '| ID | Boundary | Sender -> receiver | Request | Result |', '|---|---|---|---|---|']
    for b in bs:
        rq = f"`{b['request']}`"
        rs = f"`{b['result']}`" if b['result'] else 'none (one-way)'
        out.append(f"| [{b['id']}](#{b['id'].lower()}) | {b['name']} | {b['sender']} -> {b['receiver']} | {rq} | {rs} |")
    for b in bs:
        valid, invalid, why = examples(b['request'], b.get('request_case'))
        res = f"`{b['result']}`" if b['result'] else 'none (one-way)'
        out += ['', f"## {b['id']}", '', f"**{b['name']}**", '',
                f"| | |\n|---|---|\n| Sender | {b['sender']} |\n| Receiver | {b['receiver']} |\n| Transport | {b['transport']} |\n| Request | `{b['request']}` |\n| Result | {res} |\n| Story / demo | {b['story']} / {b['demo']} |",
                '', f"**On failure:** {b['failure']}", '', '**A valid request**', '', '```json', short(valid), '```', '',
                f'**A rejected request** (rejected because: {why})', '', '```json', short(invalid), '```']
        if b['result']:
            rvalid, rinvalid, rwhy = examples(b['result'], b.get('result_case'))
            out += ['', '**A valid result**', '', '```json', short(rvalid), '```', '',
                    f'**A rejected result** (rejected because: {rwhy})', '', '```json', short(rinvalid), '```']
        else:
            out += ['', '**No result message (one-way).** The sender gets no reply message; success and failure show in the receiver behavior described above.']
    return '\n'.join(out) + '\n'


def main():
    text = render()
    path = C / 'boundaries.md'
    cur = path.read_text(encoding='utf-8') if path.exists() else ''
    if CHECK:
        ok = cur == text
        print('boundary sheets ' + ('current' if ok else 'STALE'))
        return 0 if ok else 1
    path.write_text(text, encoding='utf-8', newline='\n')
    print(f'wrote {path.relative_to(V)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
